name: Ntalk (builder & publiher)

on:
  push:
    tags:
      - 'v*' # Запуск только при создании тега версии

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Linter run
        run: npm run lint

      - name: Build App
        run: npm run make

      - name: Create Release and Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.NTALK_TOKEN }}
        run: |
          gh release create $(git describe --tags) \
            --title "Release $(git describe --tags)" \
            --notes "Automated release" \
            --repo ilrosch/Ntalk \
            --token $GITHUB_TOKEN \
            dist/*/*.zip dist/*/*.exe dist/*.deb dist/*.rpm
